version: 2
updates:
  - package-ecosystem: terraform
    directories: ["/terraform/envs/staging", "/terraform/envs/production"]
    schedule: { interval: weekly }
    target-branch: develop
  - package-ecosystem: github-actions
    directory: "/"
    schedule: { interval: weekly }
    target-branch: develop
